'''
Created on Feb 21, 2016

@author: Martin Koerner <info@mkoerner.de>
'''

import geoip2.database
import socket
from urlparse import urlsplit

import argparse

# generate help text for arguments
parser = argparse.ArgumentParser(description='Extracts locations (country ISO code) from a file containing URLs')
parser.add_argument('input',
                   help='a file path to the output file generated by this program')
parser.add_argument("--output", dest="output", metavar='output path', type=str)
parser.add_argument("--database", dest="database", metavar='path to mmdb country database', type=str)
args = parser.parse_args()

inputfile_path=args.input
outputfile_path=args.output
databse_path=args.database

reader = open (inputfile_path,'rb')
writer = open (outputfile_path,"wb") 

# This creates a Reader object. You should use the same object
# across multiple requests as creation of it is expensive.
db_reader = geoip2.database.Reader(databse_path)

for line in reader:
    line = line.rstrip('\n')
    ip = socket.gethostbyname(urlsplit(line).netloc)

    # Replace "city" with the method corresponding to the database
    # that you are using, e.g., "country".
    response = db_reader.country(ip)
    
    writer.write(line + "\t" + response.country.iso_code+"\n")
    
reader.close()